 
import { ProductProps, ProductWidgetProps, TestimonialProps } from "./types";
import { templateImages } from "@/appProvider/templateImages";

export const featuredProducts = [
     {
          productImageAlt: "product",
          productCategory: "CATEGORY",
          productImageUrl: templateImages.demo21.specialImage.special1,
          productImageUrlTwo: '',
          productTitle: "Casual Note Bag",
          productPrice: 299,
     },
     {
          productImageAlt: "product",
          productCategory: "CAPS, DRESS",
          productImageUrl: templateImages.demo21.specialImage.special2,
          productImageUrlTwo: '',
          productTitle: "Blue Backpack",
          productPrice: 299.0,
     },
     {
          productImageAlt: "product",
          productCategory: "CAPS, T-SHIRTS",
          productImageUrl: templateImages.demo21.specialImage.special3,
          productImageUrlTwo: '',
          productTitle: "Battery Charger",
          productPrice: 259,
     },
     {
          productImageAlt: "product",
          productCategory: "DRESS, T-SHIRTS",
          productImageUrl: templateImages.demo21.specialImage.special4,
          productImageUrlTwo: '',
          productTitle: "Computer Mouse",
          productPrice: 49,
     },
     {
          productImageAlt: "product",
          productCategory: "DRESS, T-SHIRTS",
          productImageUrl: templateImages.demo21.specialImage.special5,
          productImageUrlTwo: '',
          productTitle: "Computer Mouse",
          productPrice: 49,
     },
     {
          productImageAlt: "product",
          productCategory: "DRESS, T-SHIRTS",
          productImageUrl: templateImages.demo21.specialImage.special6,
          productImageUrlTwo:  '',
          productTitle: "Computer Mouse",
          productPrice: 49,
     },
];
export const newArrivalsProducts = [
     {
          productImageAlt: "product",
          productCategory: "CATEGORY",
          productImageUrl: templateImages.demo21.specialImage.special7,
          productImageUrlTwo: '',
          productTitle: "Casual Note Bag",
          productPrice: 299,
     },
     {
          productImageAlt: "product",
          productCategory: "CAPS, DRESS",
          productImageUrl: templateImages.demo21.specialImage.special1,
          productImageUrlTwo: '',
          productTitle: "Blue Backpack",
          productPrice: 299.0,
     },
     {
          productImageAlt: "product",
          productCategory: "CAPS, T-SHIRTS",
          productImageUrl: templateImages.demo21.specialImage.special2,
          productImageUrlTwo: '',
          productTitle: "Battery Charger",
          productPrice: 259,
     },
     {
          productImageAlt: "product",
          productCategory: "DRESS, T-SHIRTS",
          productImageUrl: templateImages.demo21.specialImage.special8,
          productImageUrlTwo:  '',
          productTitle: "Computer Mouse",
          productPrice: 49,
     },
     {
          productImageAlt: "product",
          productCategory: "DRESS, T-SHIRTS",
          productImageUrl: templateImages.demo21.specialImage.special7,
          productImageUrlTwo: '',
          productTitle: "Computer Mouse",
          productPrice: 49,
     },
     {
          productImageAlt: "product",
          productCategory: "DRESS, T-SHIRTS",
          productImageUrl: templateImages.demo21.specialImage.special9,
          productImageUrlTwo: '',
          productTitle: "Computer Mouse",
          productPrice: 49,
     },
];
export const bestsellersProducts = [
     {
          productImageAlt: "product",
          productCategory: "CATEGORY",
          productImageUrl: templateImages.demo21.specialImage.special1,
          productImageUrlTwo:templateImages.demo21.specialImage.special2,
          productTitle: "Casual Note Bag",
          productPrice: 299,
     },
     {
          productImageAlt: "product",
          productCategory: "CAPS, DRESS",
          productImageUrl: templateImages.demo21.specialImage.special2,
          productImageUrlTwo: templateImages.demo21.specialImage.special1,
          productTitle: "Blue Backpack",
          productPrice: 299.0,
     },
     {
          productImageAlt: "product",
          productCategory: "CAPS, T-SHIRTS",
          productImageUrl: templateImages.demo21.specialImage.special3,
          productImageUrlTwo: templateImages.demo21.specialImage.special2,
          productTitle: "Battery Charger",
          productPrice: 259,
     },
     {
          productImageAlt: "product",
          productCategory: "DRESS, T-SHIRTS",
          productImageUrl: templateImages.demo21.specialImage.special4,
          productImageUrlTwo: templateImages.demo21.specialImage.special1,
          productTitle: "Computer Mouse",
          productPrice: 49,
     },
];
export const audiospeakers  = [
     {
          productImageAlt: "product",
          productCategory: "CATEGORY",
          productImageUrl: templateImages.demo21.specialImage.special5,
          productImageUrlTwo: templateImages.demo21.specialImage.special2,
          productTitle: " Black Grey Headset",
          productPrice: 39.0,
     },
     {
          productImageAlt: "product",
          productCategory: "CAPS, DRESS",
          productImageUrl: templateImages.demo21.specialImage.special2,
          productImageUrlTwo: templateImages.demo21.specialImage.special1,
          productTitle: "Blue Backpack",
          productPrice: 299.0,
     },
     {
          productImageAlt: "product",
          productCategory: "CAPS, T-SHIRTS",
          productImageUrl: templateImages.demo21.specialImage.special3,
          productImageUrlTwo: templateImages.demo21.specialImage.special2,
          productTitle: "Computer Mouse",
          productPrice: 259,
     },
     {
          productImageAlt: "product",
          productCategory: "DRESS, T-SHIRTS",
          productImageUrl: templateImages.demo21.specialImage.special6,
          productImageUrlTwo: templateImages.demo21.specialImage.special3,
          productTitle: "Digital Camera 16x",
          productPrice: 101.0,
     },
];
export const cameras  = [
     {
          productImageAlt: "product",
          productCategory: "CATEGORY",
          productImageUrl: templateImages.demo21.specialImage.special5,
          productImageUrlTwo: templateImages.demo21.specialImage.special2,
          productTitle: " Black Grey Headset",
          productPrice: 39.0,
     },
     {
          productImageAlt: "product",
          productCategory: "CAPS, DRESS",
          productImageUrl: templateImages.demo21.specialImage.special2,
          productImageUrlTwo: templateImages.demo21.specialImage.special3,
          productTitle: "Blue Backpack",
          productPrice: 299.0,
     },
     {
          productImageAlt: "product",
          productCategory: "DRESS, T-SHIRTS",
          productImageUrl: templateImages.demo21.specialImage.special6,
          productImageUrlTwo: templateImages.demo21.specialImage.special5,
          productTitle: "Digital Camera 16x",
          productPrice: 101.0,
     },
     {
          productImageAlt: "product",
          productCategory: "DRESS, T-SHIRTS",
          productImageUrl: templateImages.demo21.specialImage.special7,
          productImageUrlTwo: templateImages.demo21.specialImage.special2,
          productTitle: "Porto Extended Camera",
          productPrice: 599.0,
     },
];

export const lamps  = [
     {
          productImageAlt: "product",
          productCategory: "CATEGORY",
          productImageUrl: templateImages.demo21.specialImage.special8,
          productImageUrlTwo: templateImages.demo21.specialImage.special9,
          productTitle: "  Brown Bag",
          productPrice: 299.0,
     },
     {
          productImageAlt: "product",
          productCategory: "CAPS, DRESS",
          productImageUrl: templateImages.demo21.specialImage.special9,
          productImageUrlTwo: templateImages.demo21.specialImage.special2,
          productTitle: "Casual Note Bag",
          productPrice: 299.0,
     },
     {
          productImageAlt: "product",
          productCategory: "DRESS, T-SHIRTS",
          productImageUrl: templateImages.demo21.specialImage.special10,
          productImageUrlTwo: templateImages.demo21.specialImage.special8,
          productTitle: " Laptop Case Bag",
          productPrice: 1999.0,
     },
];
export const computers  = [
     {
          productImageAlt: "product",
          productCategory: "CATEGORY",
          productImageUrl: templateImages.demo21.specialImage.special11,
          productImageUrlTwo: templateImages.demo21.specialImage.special5,
          productTitle: " 1080p Wifi Ip Camera",
          productPrice: 299.0,
     },
     {
          productImageAlt: "product",
          productCategory: "CAPS, DRESS",
          productImageUrl: templateImages.demo21.specialImage.special4,
          productImageUrlTwo: templateImages.demo21.specialImage.special2,
          productTitle: "Battery Charger",
          productPrice: 299.0,
     },
     {
          productImageAlt: "product",
          productCategory: "DRESS, T-SHIRTS",
          productImageUrl: templateImages.demo21.specialImage.special5,
          productImageUrlTwo: templateImages.demo21.specialImage.special4,
          productTitle: " Black Grey Headset",
          productPrice: 29.0,
     },
     {
          productImageAlt: "product",
          productCategory: "DRESS, T-SHIRTS",
          productImageUrl: templateImages.demo21.specialImage.special2,
          productImageUrlTwo: templateImages.demo21.specialImage.special3,
          productTitle: " Blue Backpack",
          productPrice: 299.0,
     },
];
export const mobilephones  = [
     {
          productImageAlt: "product",
          productCategory: "CAPS, DRESS",
          productImageUrl: templateImages.demo21.specialImage.special2,
          productImageUrlTwo: templateImages.demo21.specialImage.special3,
          productTitle: "Blue Backpack",
          productPrice: 299.0,
     },
     {
          productImageAlt: "product",
          productCategory: "CAPS, DRESS",
          productImageUrl: templateImages.demo21.specialImage.special12,
          productImageUrlTwo: templateImages.demo21.specialImage.special9,
          productTitle: "Black Porto Men Shoes",
          productPrice: 111.0,
     },
     {
          productImageAlt: "product",
          productCategory: "DRESS, T-SHIRTS",
          productImageUrl: templateImages.demo21.specialImage.special13,
          productImageUrlTwo: templateImages.demo21.specialImage.special12,
          productTitle: "  Sports Shoes",
          productPrice: 101.0,
     },
     {
          productImageAlt: "product",
          productCategory: "DRESS, T-SHIRTS",
          productImageUrl: templateImages.demo21.specialImage.special14,
          productImageUrlTwo: templateImages.demo21.specialImage.special3,
          productTitle: " Casual Blue Shoes",
          productPrice: 101.0,
     },
];
export const topRatedProduct = [
     {
          productImageAlt: "product",
          productCategory: "CAPS, DRESS",
          productImageUrl: templateImages.demo21.specialImage.special2,
          productImageUrlTwo: templateImages.demo21.specialImage.special2,
          productTitle: " Casual Blue Shoes",
          productPrice: 101.0,
     },
     {
          productImageAlt: "product",
          productCategory: "CAPS, DRESS",
          productImageUrl: templateImages.demo21.specialImage.special12,
          productImageUrlTwo: templateImages.demo21.specialImage.special12,
          productTitle: "1080p Wifi IP Camera",
          productPrice: 299.0,
     },
     {
          productImageAlt: "product",
          productCategory: "DRESS, T-SHIRTS",
          productImageUrl: templateImages.demo21.specialImage.special13,
          productImageUrlTwo: templateImages.demo21.specialImage.special13,
          productTitle: "  Blue BackPack",
          productPrice: 299.0,
     },
];
export const topSellingProduct  = [
     {
          productImageAlt: "product",
          productCategory: "CAPS, DRESS",
          productImageUrl: templateImages.demo21.specialImage.special2,
          productImageUrlTwo: templateImages.demo21.specialImage.special2,
          productTitle: " Casual Blue Shoes",
          productPrice: 101.0,
     },
     {
          productImageAlt: "product",
          productCategory: "CAPS, DRESS",
          productImageUrl: templateImages.demo21.specialImage.special12,
          productImageUrlTwo: templateImages.demo21.specialImage.special12,
          productTitle: "1080p Wifi IP Camera",
          productPrice: 299.0,
     },
     {
          productImageAlt: "product",
          productCategory: "DRESS, T-SHIRTS",
          productImageUrl: templateImages.demo21.specialImage.special13,
          productImageUrlTwo: templateImages.demo21.specialImage.special13,
          productTitle: "  Blue BackPack",
          productPrice: 299.0,
     },
];
 
export const onSaleProduct  = [
     {
          productImageAlt: "product",
          productCategory: "CAPS, DRESS",
          productImageUrl: templateImages.demo21.specialImage.special2,
          productImageUrlTwo: templateImages.demo21.specialImage.special2,
          productTitle: " Casual Blue Shoes",
          productPrice: 101.0,
     },
     {
          productImageAlt: "product",
          productCategory: "CAPS, DRESS",
          productImageUrl: templateImages.demo21.specialImage.special12,
          productImageUrlTwo: templateImages.demo21.specialImage.special12,
          productTitle: "1080p Wifi IP Camera",
          productPrice: 299.0,
     },
     {
          productImageAlt: "product",
          productCategory: "DRESS, T-SHIRTS",
          productImageUrl: templateImages.demo21.specialImage.special13,
          productImageUrlTwo: templateImages.demo21.specialImage.special13,
          productTitle: "  Blue BackPack",
          productPrice: 299.0,
     },
];
