import { templateImages } from "@/appProvider/templateImages";

export const infoData = [
     {
          h4: "Free Shipping on Orders Over $99",
          p: "For more than 100,000 parts!",
          icon: "icon-shipping text-primary",
     },
     {
          h4: "Up to 40% OFF on Selected Items",
          p: "Available for all Categories!",
          icon: "icon-percent-circle text-primary",
     },
     {
          h4: "100% Secure Payment",
          p: "We ensure secure payment!",
          icon: "icon-pulley text-primary",
     },
];
export const productinfo = [
     {
          productImageAlt: "product",
          productCategory: "CATEGORY",
          productImageUrl: templateImages.demo37.productImages.product1,
          productImageUrlTwo: "",
          productTitle: "Wrist Watch",
          productPrice: 299.0,
     },
     {
          productImageAlt: "product",
          productCategory: "CAPS, DRESS",
          productImageUrl: templateImages.demo37.productImages.product8,
          productImageUrlTwo: "",
          productTitle: "Belt",
          productPrice: 25.0,
     },
     {
          productImageAlt: "product",
          productCategory: "CAPS, T-SHIRTS",
          productImageUrl: templateImages.demo37.productImages.product4,
          productImageUrlTwo: "",
          productTitle: " Man Shaggy Coat",
          productPrice: 259.0,
     },
     {
          productImageAlt: "product",
          productCategory: "DRESS, T-SHIRTS",
          productImageUrl: templateImages.demo37.productImages.product9,
          productImageUrlTwo: "",
          productTitle: "Blue Tshirt",
          productPrice: 49,
     },
     {
          productImageAlt: "product",
          productCategory: "DRESS, T-SHIRTS",
          productImageUrl: templateImages.demo37.productImages.product10,
          productImageUrlTwo: "",
          productTitle: "Lingerie",
          productPrice: 49,
     },
     {
          productImageAlt: "product",
          productCategory: "DRESS, T-SHIRTS",
          productImageUrl: templateImages.demo37.productImages.product11,
          productImageUrlTwo: "",
          productTitle: "Black Handbag",
          productPrice: 49,
     },
];
export const productinfo2 = [
     {
          productImageAlt: "product",
          productCategory: "CATEGORY",
          productImageUrl: templateImages.demo37.productImages.product9,
          productImageUrlTwo: "",
          productTitle: "Wrist Watch",
          productPrice: 299.0,
          position: "dot-top-one",
          atag: "demo37-shop.html",
     },
     {
          productImageAlt: "product",
          productCategory: "CAPS, DRESS",
          productImageUrl: templateImages.demo37.productImages.product6,
          productImageUrlTwo: "",
          productTitle: "Belt",
          productPrice: 25.0,
          position: "dot-middle-one",
          atag: "demo37-shop.html",
     },
     {
          productImageAlt: "product",
          productCategory: "CAPS, T-SHIRTS",
          productImageUrl: templateImages.demo37.productImages.product10,
          productImageUrlTwo: "",
          productTitle: " Man Shaggy Coat",
          productPrice: 259.0,
          position: "dot-bottom-one",
          atag: "demo37-shop.html",
     },
     {
          productImageAlt: "product",
          productCategory: "DRESS, T-SHIRTS",
          productImageUrl: templateImages.demo37.productImages.product5,
          productImageUrlTwo: "",
          productTitle: "Blue Tshirt",
          productPrice: 49,
          position: "dot-top-two",
          atag: "demo37-shop.html",
     },
     {
          productImageAlt: "product",
          productCategory: "DRESS, T-SHIRTS",
          productImageUrl: templateImages.demo37.productImages.product3,
          productImageUrlTwo: "",
          productTitle: "Lingerie",
          productPrice: 49,
          position: "dot-middle-two",
          atag: "demo37-shop.html",
     },
     {
          productImageAlt: "product",
          productCategory: "DRESS, T-SHIRTS",
          productImageUrl: templateImages.demo37.productImages.product4,
          productImageUrlTwo: "",
          productTitle: "Black Handbag",
          productPrice: 49,
          position: "dot-bottom-two",
          atag: "demo37-shop.html",
     },
];
export const productScrolls = [
     {
          productImageAlt: "product",
          productCategory: "CATEGORY",
          productImageUrl: templateImages.demo37.productImages.product1,
          productImageUrlTwo: "",
          productTitle: "Casual Note Bag",
          productPrice: 299,
     },
     {
          productImageAlt: "product",
          productCategory: "CAPS, DRESS",
          productImageUrl: templateImages.demo37.productImages.product2,
          productImageUrlTwo: "",
          productTitle: "Blue Backpack",
          productPrice: 299.0,
     },
     {
          productImageAlt: "product",
          productCategory: "CAPS, T-SHIRTS",
          productImageUrl: templateImages.demo37.productImages.product3,
          productImageUrlTwo: "",
          productTitle: "Battery Charger",
          productPrice: 259,
     },
     {
          productImageAlt: "product",
          productCategory: "DRESS, T-SHIRTS",
          productImageUrl: templateImages.demo37.productImages.product4,
          productImageUrlTwo: "",
          productTitle: "Computer Mouse",
          productPrice: 49,
     },
     {
          productImageAlt: "product",
          productCategory: "DRESS, T-SHIRTS",
          productImageUrl: templateImages.demo37.productImages.product5,
          productImageUrlTwo: "",
          productTitle: "Computer Mouse",
          productPrice: 49,
     },
     {
          productImageAlt: "product",
          productCategory: "DRESS, T-SHIRTS",
          productImageUrl: templateImages.demo37.productImages.product6,
          productImageUrlTwo: "",
          productTitle: "Computer Mouse",
          productPrice: 49,
     },
     {
          productImageAlt: "product",
          productCategory: "DRESS, T-SHIRTS",
          productImageUrl: templateImages.demo37.productImages.product7,
          productImageUrlTwo: "",
          productTitle: "Computer Mouse",
          productPrice: 49,
     },
     {
          productImageAlt: "product",
          productCategory: "DRESS, T-SHIRTS",
          productImageUrl: templateImages.demo37.productImages.product8,
          productImageUrlTwo: "",
          productTitle: "Computer Mouse",
          productPrice: 49,
     },
     {
          productImageAlt: "product",
          productCategory: "DRESS, T-SHIRTS",
          productImageUrl: templateImages.demo37.productImages.product9,
          productImageUrlTwo: "",
          productTitle: "Computer Mouse",
          productPrice: 49,
     },
     {
          productImageAlt: "product",
          productCategory: "DRESS, T-SHIRTS",
          productImageUrl: templateImages.demo37.productImages.product10,
          productImageUrlTwo: "",
          productTitle: "Computer Mouse",
          productPrice: 49,
     },
];
export const SaleProducts = [
     {
          productImageAlt: "product",
          productCategory: "CATEGORY",
          productImageUrl: templateImages.demo37.productImages.product6,
          productImageUrlTwo: "",
          productTitle: "Casual Note Bag",
          productPrice: 299,
     },
     {
          productImageAlt: "product",
          productCategory: "CAPS, DRESS",
          productImageUrl: templateImages.demo37.productImages.product4,
          productImageUrlTwo: "",
          productTitle: "Blue Backpack",
          productPrice: 299.0,
     },
     {
          productImageAlt: "product",
          productCategory: "CAPS, T-SHIRTS",
          productImageUrl: templateImages.demo37.productImages.product6,
          productImageUrlTwo: "",
          productTitle: "Battery Charger",
          productPrice: 259,
     },
     {
          productImageAlt: "product",
          productCategory: "DRESS, T-SHIRTS",
          productImageUrl: templateImages.demo37.productImages.product2,
          productImageUrlTwo: "",
          productTitle: "Computer Mouse",
          productPrice: 49,
     },
     {
          productImageAlt: "product",
          productCategory: "DRESS, T-SHIRTS",
          productImageUrl: templateImages.demo37.productImages.product3,
          productImageUrlTwo: "",
          productTitle: "Computer Mouse",
          productPrice: 49,
     },
     {
          productImageAlt: "product",
          productCategory: "DRESS, T-SHIRTS",
          productImageUrl: templateImages.demo37.productImages.product7,
          productImageUrlTwo: "",
          productTitle: "Computer Mouse",
          productPrice: 49,
     },
];
export const newArrivalsProducts = [
     {
          productImageAlt: "product",
          productCategory: "CATEGORY",
          productImageUrl: templateImages.demo37.productImages.product7,
          productImageUrlTwo: "",
          productTitle: "Casual Note Bag",
          productPrice: 299,
     },
     {
          productImageAlt: "product",
          productCategory: "CAPS, DRESS",
          productImageUrl: templateImages.demo37.productImages.product8,
          productImageUrlTwo: "",
          productTitle: "Blue Backpack",
          productPrice: 299.0,
     },
     {
          productImageAlt: "product",
          productCategory: "CAPS, T-SHIRTS",
          productImageUrl: templateImages.demo37.productImages.product4,
          productImageUrlTwo: "",
          productTitle: "Battery Charger",
          productPrice: 259,
     },
     {
          productImageAlt: "product",
          productCategory: "DRESS, T-SHIRTS",
          productImageUrl: templateImages.demo37.productImages.product9,
          productImageUrlTwo: "",
          productTitle: "Computer Mouse",
          productPrice: 49,
     },
     {
          productImageAlt: "product",
          productCategory: "DRESS, T-SHIRTS",
          productImageUrl: templateImages.demo37.productImages.product10,
          productImageUrlTwo: "",
          productTitle: "Computer Mouse",
          productPrice: 49,
     },
     {
          productImageAlt: "product",
          productCategory: "DRESS, T-SHIRTS",
          productImageUrl: templateImages.demo37.productImages.product11,
          productImageUrlTwo: "",
          productTitle: "Computer Mouse",
          productPrice: 49,
     },
];
export const slidersData = [
     {
          slideImage: templateImages.demo37.sliderImage.slider1,
          sliderImage2: templateImages.demo37.bannerImage.banner4,
          h4: "Find the Boundaries. Push Through!",
          h2: " SUNGLASSES",
          link: "demo37-shop.html",
     },
     {
          slideImage: templateImages.demo37.sliderImage.slider2,
          sliderImage2: templateImages.demo37.bannerImage.banner4,
          h4: " Take Your Chill Up a Level",
          h2: "CASUAL WEAR",
          link: "demo37-shop.html",
          left: "50.9%",
     },
];

export const CatData = [
     {
          link: "demo37-shop.html",
          atag: "Women",
          img: templateImages.demo37.categoryImage.category1,
     },
     {
          link: "demo37-shop.html",
          atag: "Men",
          img: templateImages.demo37.categoryImage.category2,
     },
     {
          link: "demo37-shop.html",
          atag: "Girls",
          img: templateImages.demo37.categoryImage.category3,
     },
     {
          link: "demo37-shop.html",
          atag: "Boys",
          img: templateImages.demo37.categoryImage.category4,
     },
     {
          link: "demo37-shop.html",
          atag: "Baby",
          img: templateImages.demo37.categoryImage.category5,
     },
     {
          link: "demo37-shop.html",
          atag: "Shoes",
          img: templateImages.demo37.categoryImage.category6,
     },
     {
          link: "demo37-shop.html",
          atag: "Jewelry",
          img: templateImages.demo37.categoryImage.category7,
     },
     {
          link: "demo37-shop.html",
          atag: "Underwear",
          img: templateImages.demo37.categoryImage.category8,
     },
     {
          link: "demo37-shop.html",
          atag: "Accessories",
          img: templateImages.demo37.categoryImage.category9,
     },
     {
          link: "demo37-shop.html",
          atag: "New Arrivals",
          img: templateImages.demo37.categoryImage.category10,
     },
     {
          link: "demo37-shop.html",
          atag: " Sale",
          img: templateImages.demo37.categoryImage.category6,
     },
];
export const payments = [
     {
          image: templateImages.paymentImage.payment4,
     },
     {
          image: templateImages.paymentImage.payment1,
     },
     {
          image: templateImages.paymentImage.payment2,
     },
     {
          image: templateImages.paymentImage.payment3,
     },
];
