import { ProductProps } from "./types";
import { templateImages } from "@/appProvider/templateImages";

export const products: ProductProps[] = [
     {
          productImageAlt: "product",
          productCategory: "SHOES, TOYS",
          productImageUrl: templateImages.demo19.productImages.product1,
          productTitle: "Men Gentle Shoes",
          productPrice: 269,
     },
     {
          productImageAlt: "product",
          productCategory: "CAPS, DRESS",
          productImageUrl: templateImages.demo19.productImages.product2,
          productTitle: "Porto Gray Cap",
          productPrice: 29,
     },
     {
          productImageAlt: "product",
          productCategory: "CAPS, T-SHIRTS",
          productImageUrl: templateImages.demo19.productImages.product3,
          productTitle: "Porto White Cap",
          productPrice: 101,
     },
     {
          productImageAlt: "product",
          productCategory: "DRESS, T-SHIRTS",
          productImageUrl: templateImages.demo19.productImages.product4,
          productTitle: "Winter Towel",
          productPrice: 49,
     },
     {
          productImageAlt: "product",
          productCategory: "DRESS, HEADPHONE",
          productImageUrl: templateImages.demo19.productImages.product5,
          productTitle: "Product Extended",
          productPrice: 49,
     },
     {
          productImageAlt: "product",
          productCategory: "SHOES, TOYS",
          productImageUrl: templateImages.demo19.productImages.product6,
          productTitle: "Sports Shoes",
          productPrice: 239,
     },
     {
          productImageAlt: "product",
          productCategory: "TOYS, TROUSERS",
          productImageUrl: templateImages.demo19.productImages.product7,
          productTitle: "Women Bag",
          productPrice: 299,
     },
     {
          productImageAlt: "product",
          productCategory: "HEADPHONE, WATCHES",
          productImageUrl: templateImages.demo19.productImages.product8,
          productTitle: "Men Black Belts",
          productPrice: 55,
     },
     {
          productImageAlt: "product",
          productCategory: "DRESS, WATCHES",
          productImageUrl: templateImages.demo19.productImages.product9,
          productTitle: "Women Bag",
          productPrice: 199,
     },
     {
          productImageAlt: "product",
          productCategory: "category",
          productImageUrl: templateImages.demo19.productImages.product10,
          productTitle: "Men Black Jacket",
          productPrice: 49,
          oldPrice: 59,
     },
     {
          productImageAlt: "product",
          productCategory: "category",
          productImageUrl: templateImages.demo19.productImages.product11,
          productTitle: "Black Women Shoes",
          productPrice: 49,
          oldPrice: 59,
     },
     {
          productImageAlt: "product",
          productCategory: "category",
          productImageUrl: templateImages.demo19.productImages.product12,
          productTitle: "Black Men Carousel Melt",
          productPrice: 49,
          oldPrice: 59,
     },
     {
          productImageAlt: "product",
          productCategory: "category",
          productImageUrl: templateImages.demo19.productImages.product13,
          productTitle: "Blue Sports Clothes",
          productPrice: 49,
          oldPrice: 59,
     },
     {
          productImageAlt: "product",
          productCategory: "category",
          productImageUrl: templateImages.demo19.productImages.product14,
          productTitle: "Blue Spring Casual Shoes",
          productPrice: 49,
          oldPrice: 59,
     },
     {
          productImageAlt: "product",
          productCategory: "category",
          productImageUrl: templateImages.demo19.productImages.product15,
          productTitle: "Grey Men Sports Cap",
          productPrice: 49,
          oldPrice: 59,
     },
     {
          productImageAlt: "product",
          productCategory: "category",
          productImageUrl: templateImages.demo19.productImages.product16,
          productTitle: "Men Black Jacket",
          productPrice: 49,
          oldPrice: 59,
     },
     {
          productImageAlt: "product",
          productCategory: "category",
          productImageUrl: templateImages.demo19.productImages.product17,
          productTitle: "Porto Brown Bag",
          productPrice: 49,
          oldPrice: 59,
     },
     {
          productImageAlt: "product",
          productCategory: "category",
          productImageUrl: templateImages.demo19.productImages.product18,
          productTitle: "Black Men Carousel Melt",
          productPrice: 49,
          oldPrice: 59,
     },
     {
          productImageAlt: "product",
          productCategory: "category",
          productImageUrl: templateImages.demo19.productImages.product19,
          productTitle: "Blue Spring Casual Shoes",
          productPrice: 49,
          oldPrice: 59,
     },
     {
          productImageAlt: "product",
          productCategory: "category",
          productImageUrl: templateImages.demo19.productImages.product20,
          productTitle: "Grey Men Sports Cap",
          productPrice: 49,
          oldPrice: 59,
     },
     // Add more latest products as needed
     {
          productImageAlt: "product",
          productCategory: "category",
          productImageUrl: templateImages.demo19.productImages.product21,
          productTitle: "Porto Brown Bag",
          productPrice: 49,
          oldPrice: 59,
     },
     {
          productImageAlt: "product",
          productCategory: "category",
          productImageUrl: templateImages.demo19.productImages.product22,
          productTitle: "Blue Spring Casual Shoes",
          productPrice: 49,
          oldPrice: 59,
     },
     {
          productImageAlt: "product",
          productCategory: "category",
          productImageUrl: templateImages.demo19.productImages.product23,
          productTitle: "Grey Men Sports Cap",
          productPrice: 49,
          oldPrice: 59,
     },
     {
          productImageAlt: "product",
          productCategory: "category",
          productImageUrl: templateImages.demo19.productImages.product24,
          productTitle: "Men Black Jacket",
          productPrice: 49,
          oldPrice: 59,
     },
     {
          productImageAlt: "product",
          productCategory: "category",
          productImageUrl: templateImages.demo19.productImages.product25,
          productTitle: "Porto Brown Bag",
          productPrice: 49,
          oldPrice: 59,
     },
     {
          productImageAlt: "product",
          productCategory: "category",
          productImageUrl: templateImages.demo19.productImages.product26,
          productTitle: "Men Black Jacket",
          productPrice: 49,
          oldPrice: 59,
     },
     {
          productImageAlt: "product",
          productCategory: "category",
          productImageUrl: templateImages.demo19.productImages.product27,
          productTitle: "Black Women Shoes",
          productPrice: 49,
          oldPrice: 59,
     },
     {
          productImageAlt: "product",
          productCategory: "category",
          productImageUrl: templateImages.demo19.productImages.product28,
          productTitle: "Black Men Carousel Melt",
          productPrice: 49,
          oldPrice: 59,
     },
     {
          productImageAlt: "product",
          productCategory: "category",
          productImageUrl: templateImages.demo19.productImages.product29,
          productTitle: "Blue Sports Clothes",
          productPrice: 49,
          oldPrice: 59,
     },
     {
          productImageAlt: "product",
          productCategory: "category",
          productImageUrl: templateImages.demo19.productImages.product30,
          productTitle: "Blue Sports Clothes",
          productPrice: 49,
          oldPrice: 59,
     },
     {
          productImageAlt: "product",
          productCategory: "category",
          productImageUrl: templateImages.demo19.productImages.product31,
          productTitle: "Blue Sports Clothes",
          productPrice: 49,
          oldPrice: 59,
     },
     {
          productImageAlt: "product",
          productCategory: "category",
          productImageUrl: templateImages.demo19.productImages.product32,
          productTitle: "Blue Sports Clothes",
          productPrice: 49,
          oldPrice: 59,
     },
     {
          productImageAlt: "product",
          productCategory: "category",
          productImageUrl: templateImages.demo19.productImages.product33,
          productTitle: "Blue Sports Clothes",
          productPrice: 49,
          oldPrice: 59,
     },
     {
          productImageAlt: "product",
          productCategory: "category",
          productImageUrl: templateImages.demo19.productImages.product34,
          productTitle: "Blue Sports Clothes",
          productPrice: 49,
          oldPrice: 59,
     },
     {
          productImageAlt: "product",
          productCategory: "category",
          productImageUrl: templateImages.demo19.productImages.product35,
          productTitle: "Blue Sports Clothes",
          productPrice: 49,
          oldPrice: 59,
     },
     {
          productImageAlt: "product",
          productCategory: "category",
          productImageUrl: templateImages.demo19.productImages.product36,
          productTitle: "Blue Sports Clothes",
          productPrice: 49,
          oldPrice: 59,
     },
];
