/* eslint-disable @next/next/no-css-tags */
"use client";
import AppProvider from "@/appProvider";
import "./globals.css";
// import "bootstrap/dist/css/bootstrap.min.css";
// import "bootstrap/dist/js/bootstrap.bundle.min";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import $ from "jquery";
import Popper from "popper.js";
import Script from "next/script";
import Head from "next/head";
import "../assets/css/bootstrap.min.css";
import "../assets/css/demo13.min.css";
import "../assets/vendor/fontawesome-free/css/all.min.css";
import "../assets/vendor/simple-line-icons/css/simple-line-icons.min.css";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//      title: "Create Next App",
//      description: "Generated by create next app",
// };

export default function RootLayout({ children }: { children: React.ReactNode }) {
     return (
          <html lang="en">
               <Head>
                    <meta name="viewport" content="width=device-width, initial-scale=1" />
                    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>
               </Head>
               <AppProvider>{children}</AppProvider>
          </html>
     );
}
